apps/pages/urls.py
from django.urls import path

from apps.pages.views import home_page_view, ContactPageView, about_page_view

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('about/', about_page_view, name='about'),
    path('', home_page_view, name='home'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pages/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.db.models import CharField


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ContactModel(BaseModel):
    full_name = models.CharField(max_length=128)
    email = models.EmailField()
    phone_number = models.CharField(
        max_length=15, null=True, blank=True
    )
    subject = models.CharField(
        max_length=255, null=True, blank=True
    )
    message = models.TextField()

    is_read = models.BooleanField(default=False)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.full_name} - {self.email}"

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'
        permissions = [
            ("can_change_status", "Can change contact status"),
        ]


class BannerModel(BaseModel):
    image = models.ImageField(upload_to='banners/')
    title = CharField(max_length=256)
    description = RichTextUploadingField()
    text = CharField(max_length=128)
    url = models.URLField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'banner'
        verbose_name_plural = 'banners'

templates/pages/coming-soon.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}Coming soon{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery.countdown.css' %}">
{% endblock %}
{% block content %}
    <div class="soon">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-lg-8">
                    <div class="soon-content text-center">
                        <div class="soon-content-wrapper">
                            <img src="{% static 'assets/images/logo-icon.png' %}" alt="Logo" class="soon-logo mx-auto">
                            <h1 class="soon-title">Coming Soon</h1><!-- End .soon-title -->
                            <div class="coming-countdown countdown-separator"></div><!-- End .coming-countdown -->
                            <hr class="mt-2 mb-3 mt-md-3">
                            <p>We are currently working on an awesome new site. Stay tuned for more information.
                                Subscribe to our newsletter to stay updated on our progress.</p>
                            <form action="#">
                                <div class="input-group mb-5">
                                    <input type="email" class="form-control bg-transparent"
                                           placeholder="Enter your Email Address" required>
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-primary-2" type="submit">
                                            <span>SUBSCRIBE</span>
                                            <i class="icon-long-arrow-right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                            <div class="social-icons justify-content-center mb-0">
                                <a href="#" class="social-icon" target="_blank" title="Facebook"><i
                                        class="icon-facebook-f"></i></a>
                                <a href="#" class="social-icon" target="_blank" title="Twitter"><i
                                        class="icon-twitter"></i></a>
                                <a href="#" class="social-icon" target="_blank" title="Instagram"><i
                                        class="icon-instagram"></i></a>
                                <a href="#" class="social-icon" target="_blank" title="Youtube"><i
                                        class="icon-youtube"></i></a>
                                <a href="#" class="social-icon" target="_blank" title="Pinterest"><i
                                        class="icon-pinterest"></i></a>
                            </div><!-- End .soial-icons -->
                        </div><!-- End .soon-content-wrapper -->
                    </div><!-- End .soon-content -->
                </div><!-- End .col-md-9 col-lg-8 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
        <div class="soon-bg bg-image"
             style="background-image: url({% static 'assets/images/backgrounds/soon-bg.jpg' %})"></div>
        <!-- End .soon-bg bg-image -->
    </div><!-- End .soon -->
{% endblock %}
{% block extra_js %}
    <script>
        $(function () {
            "use strict";
            if ($.fn.countdown) {
                $('.coming-countdown').countdown({
                    until: new Date(2025, 10, 20), // 7th month = August / Months 0 - 11 (January  - December)
                    format: 'DHMS',
                    padZeroes: true
                });

                // Pause
                // $('.coming-countdown').countdown('pause');
            }
        });
    </script>
    <script src="{% static 'assets/js/jquery.plugin.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
{% endblock %}

templates/pages/contact.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}
{% block content %}
    <main class="main">
        <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Pages</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Contact us</li>
                </ol>
            </div><!-- End .container -->
        </nav><!-- End .breadcrumb-nav -->
        <div class="container">
            <div class="page-header page-header-big text-center"
                 style="background-image: url('{% static 'assets/images/contact-header-bg.jpg' %}')">
                <h1 class="page-title text-white">Contact us<span class="text-white">keep in touch with us</span></h1>
            </div><!-- End .page-header -->
        </div><!-- End .container -->

        <div class="page-content pb-0">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 mb-2 mb-lg-0">
                        <h2 class="title mb-1">Contact Information</h2><!-- End .title mb-2 -->
                        <p class="mb-3">Vestibulum volutpat, lacus a ultrices sagittis, mi neque euismod dui, eu
                            pulvinar nunc sapien ornare nisl. Phasellus pede arcu, dapibus eu, fermentum et, dapibus
                            sed, urna.</p>
                        <div class="row">
                            <div class="col-sm-7">
                                <div class="contact-info">
                                    <h3>The Office</h3>

                                    <ul class="contact-list">
                                        <li>
                                            <i class="icon-map-marker"></i>
                                            70 Washington Square South New York, NY 10012, United States
                                        </li>
                                        <li>
                                            <i class="icon-phone"></i>
                                            <a href="tel:#">+92 423 567</a>
                                        </li>
                                        <li>
                                            <i class="icon-envelope"></i>
                                            <a href="mailto:#">info@Molla.com</a>
                                        </li>
                                    </ul><!-- End .contact-list -->
                                </div><!-- End .contact-info -->
                            </div><!-- End .col-sm-7 -->

                            <div class="col-sm-5">
                                <div class="contact-info">
                                    <h3>The Office</h3>

                                    <ul class="contact-list">
                                        <li>
                                            <i class="icon-clock-o"></i>
                                            <span class="text-dark">Monday-Saturday</span> <br>11am-7pm ET
                                        </li>
                                        <li>
                                            <i class="icon-calendar"></i>
                                            <span class="text-dark">Sunday</span> <br>11am-6pm ET
                                        </li>
                                    </ul><!-- End .contact-list -->
                                </div><!-- End .contact-info -->
                            </div><!-- End .col-sm-5 -->
                        </div><!-- End .row -->
                    </div><!-- End .col-lg-6 -->
                    {% if perms.pages.add_contactmodel %}
                        <div class="col-lg-6">
                            <h2 class="title mb-1">Got Any Questions?</h2><!-- End .title mb-2 -->
                            <p class="mb-2">Use the form below to get in touch with the sales team</p>

                            <form method="post" action="{% url 'pages:contact' %}" class="contact-form mb-3">
                                {{ errors }}
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-6">
                                        <label for="cname" class="sr-only">Name</label>
                                        <input name="full_name" type="text" class="form-control" id="cname"
                                               placeholder="Name *" required>
                                    </div><!-- End .col-sm-6 -->

                                    <div class="col-sm-6">
                                        <label for="cemail" class="sr-only">Email</label>
                                        <input name="email" type="email" class="form-control" id="cemail"
                                               placeholder="Email *" required>
                                    </div><!-- End .col-sm-6 -->
                                </div><!-- End .row -->

                                <div class="row">
                                    <div class="col-sm-6">
                                        <label for="cphone" class="sr-only">Phone</label>
                                        <input name="phone_number" type="tel" class="form-control" id="cphone"
                                               placeholder="Phone">
                                    </div><!-- End .col-sm-6 -->

                                    <div class="col-sm-6">
                                        <label for="csubject" class="sr-only">Subject</label>
                                        <input name="subject" type="text" class="form-control" id="csubject"
                                               placeholder="Subject">
                                    </div><!-- End .col-sm-6 -->
                                </div><!-- End .row -->

                                <label for="cmessage" class="sr-only">Message</label>
                                <textarea name="message" class="form-control" cols="30" rows="4" id="cmessage" required
                                          placeholder="Message *"></textarea>

                                <button type="submit" class="btn btn-outline-primary-2 btn-minwidth-sm">
                                    <span>SUBMIT</span>
                                    <i class="icon-long-arrow-right"></i>
                                </button>
                            </form><!-- End .contact-form -->
                        </div><!-- End .col-lg-6 -->
                    {% endif %}
                </div><!-- End .row -->

                <hr class="mt-4 mb-5">

                <div class="stores mb-4 mb-lg-5">
                    <h2 class="title text-center mb-3">Our Stores</h2><!-- End .title text-center mb-2 -->

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="store">
                                <div class="row">
                                    <div class="col-sm-5 col-xl-6">
                                        <figure class="store-media mb-2 mb-lg-0">
                                            <img src="{% static 'assets/images/stores/img-1.jpg' %}" alt="image">
                                        </figure><!-- End .store-media -->
                                    </div><!-- End .col-xl-6 -->
                                    <div class="col-sm-7 col-xl-6">
                                        <div class="store-content">
                                            <h3 class="store-title">Wall Street Plaza</h3><!-- End .store-title -->
                                            <address>88 Pine St, New York, NY 10005, USA</address>
                                            <div><a href="tel:#">+1 987-876-6543</a></div>

                                            <h4 class="store-subtitle">Store Hours:</h4><!-- End .store-subtitle -->
                                            <div>Monday - Saturday 11am to 7pm</div>
                                            <div>Sunday 11am to 6pm</div>

                                            <a href="#" class="btn btn-link" target="_blank"><span>View Map</span><i
                                                    class="icon-long-arrow-right"></i></a>
                                        </div><!-- End .store-content -->
                                    </div><!-- End .col-xl-6 -->
                                </div><!-- End .row -->
                            </div><!-- End .store -->
                        </div><!-- End .col-lg-6 -->

                        <div class="col-lg-6">
                            <div class="store">
                                <div class="row">
                                    <div class="col-sm-5 col-xl-6">
                                        <figure class="store-media mb-2 mb-lg-0">
                                            <img src="{% static 'assets/images/stores/img-2.jpg' %}" alt="image">
                                        </figure><!-- End .store-media -->
                                    </div><!-- End .col-xl-6 -->

                                    <div class="col-sm-7 col-xl-6">
                                        <div class="store-content">
                                            <h3 class="store-title">One New York Plaza</h3><!-- End .store-title -->
                                            <address>88 Pine St, New York, NY 10005, USA</address>
                                            <div><a href="tel:#">+1 987-876-6543</a></div>

                                            <h4 class="store-subtitle">Store Hours:</h4><!-- End .store-subtitle -->
                                            <div>Monday - Friday 9am to 8pm</div>
                                            <div>Saturday - 9am to 2pm</div>
                                            <div>Sunday - Closed</div>

                                            <a href="#" class="btn btn-link" target="_blank"><span>View Map</span><i
                                                    class="icon-long-arrow-right"></i></a>
                                        </div><!-- End .store-content -->
                                    </div><!-- End .col-xl-6 -->
                                </div><!-- End .row -->
                            </div><!-- End .store -->
                        </div><!-- End .col-lg-6 -->
                    </div><!-- End .row -->
                </div><!-- End .stores -->
            </div><!-- End .container -->
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d47967.61739286181!2d69.22814149999999!3d41.287624900000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8ba966c0cdbf%3A0xe69be7522d8208da!2sMilliy%20Bog!5e0!3m2!1sen!2s!4v1756131648930!5m2!1sen!2s"
                    width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div><!-- End .page-content -->
    </main><!-- End .main -->
{% endblock %}

templates/pages/test-contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Test html</h1>
{{ form }}

<select name="sign" id="">
    <option value="+">+</option>
    <option value="-">-</option>
</select>
</body>
</html>