apps/blogs/urls.py
from django.urls import path

from apps.blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blogs/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

from apps.blogs.managers import BlogModelManager
from apps.pages.models import BaseModel


class BlogCategoryModel(BaseModel):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog category'
        verbose_name_plural = 'Blog categories'


class BlogTagModel(BaseModel):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog tag'
        verbose_name_plural = 'Blog tags'


class BlogAuthorModel(BaseModel):
    full_name = models.CharField(max_length=64)
    avatar = models.ImageField(
        upload_to='blog-author/'
    )
    bio = models.CharField(max_length=256)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Blog author'
        verbose_name_plural = 'Blog authors'


class BlogModel(BaseModel):
    class BlogStatus(models.TextChoices):
        DRAFT = 'DRAFT'
        PUBLISHED = 'PUBLISHED'
        DELETED = 'DELETED'

    image = models.ImageField(upload_to='blog-post/')
    title = models.CharField(max_length=255)

    content = RichTextUploadingField()

    status = models.CharField(
        max_length=20,
        choices=BlogStatus,
        default=BlogStatus.DRAFT
    )

    author = models.ForeignKey(
        BlogAuthorModel,
        on_delete=models.CASCADE,
        related_name='blogs'
    )
    category = models.ManyToManyField(
        BlogCategoryModel,
        related_name='blogs'
    )
    tag = models.ManyToManyField(
        BlogTagModel,
        related_name='blogs'
    )

    objects = BlogModelManager()

    def views_count(self):
        return self.views.distinct().count()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'


class BlogViewModel(BaseModel):
    user_ip = models.CharField(max_length=15)
    blog = models.ForeignKey(
        BlogModel, on_delete=models.CASCADE, related_name='views'
    )

    def __str__(self):
        return f"{self.user_ip} - {self.blog.id}"

    class Meta:
        verbose_name = 'Blog view'
        verbose_name_plural = 'Blog views'

apps/blogs/views.py
import threading

from django.db.models import Count
from django.views.generic import ListView, DetailView

from apps.blogs.models import BlogModel, BlogCategoryModel, BlogTagModel
from apps.blogs.utils import check_blog_view


class BlogListView(ListView):
    template_name = 'blogs/blog-list.html'

    def get_queryset(self):
        print(BlogModel.objects.all_objects().all().values_list('status'))
        print(BlogModel.objects.all().values_list('status'))
        print(BlogModel.objects.published().values_list('status'))
        return BlogModel.objects.filter(
            status=BlogModel.BlogStatus.PUBLISHED
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        categories = BlogCategoryModel.objects.all()
        tags = BlogTagModel.objects.all()
        most_popular_blogs = (
            BlogModel.objects
            .annotate(views_count=Count('views', distinct=True))
            .order_by('-views_count')[:4]
        )
        context["blogs"] = self.get_queryset()
        context["categories"] = categories
        context["tags"] = tags
        context["most_popular_blogs"] = most_popular_blogs

        return context


class BlogDetailView(DetailView):
    template_name = 'blogs/blog-detail.html'
    queryset = BlogModel.objects.all()
    context_object_name = 'blog'
    pk_url_kwarg = 'pk'
    permission_required = ['']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog = self.get_object()

        # update view count of blog
        threading.Thread(target=check_blog_view, args=(self.request, blog,)).start()

        categories = BlogCategoryModel.objects.all()
        tags = BlogTagModel.objects.all()
        related_blogs = BlogModel.objects.filter(
            category__in=blog.category.all()
        ).exclude(id=blog.id).distinct()
        most_popular_blogs = (
            BlogModel.objects
            .annotate(views_count=Count('views', distinct=True))
            .order_by('-views_count')[:4]
        )

        context["blogs"] = self.get_queryset()
        context["categories"] = categories
        context["tags"] = tags
        context["most_popular_blogs"] = most_popular_blogs
        context["related_blogs"] = related_blogs

        return context

templates/blogs/blog-left-side.html
{% load static %}
<aside class="col-lg-3">
    <div class="sidebar">
        <div class="widget widget-search">
            <h3 class="widget-title">Search</h3><!-- End .widget-title -->

            <form action="#">
                <label for="ws" class="sr-only">Search in blog</label>
                <input type="search" class="form-control" name="ws" id="ws"
                       placeholder="Search in blog" required>
                <button type="submit" class="btn"><i class="icon-search"></i><span class="sr-only">Search</span>
                </button>O
            </form>
        </div><!-- End .widget -->

        <div class="widget widget-cats">
            <h3 class="widget-title">Categories</h3><!-- End .widget-title -->

            <ul>
                {% for cat in categories %}
                    <li><a href="#">{{ cat.title }}<span>
                                            {{ cat.blogs.count }}
                                        </span></a></li>
                {% endfor %}
            </ul>
        </div><!-- End .widget -->

        <div class="widget">
            <h3 class="widget-title">Popular Posts</h3><!-- End .widget-title -->

            <ul class="posts-list">
                {% for p_blog in most_popular_blogs %}
                    <li>
                        <figure>
                            <a href="#">
                                <img src="{{ p_blog.image.url }}"
                                     alt="post">
                            </a>
                        </figure>

                        <div>
                            <span>{{ p_blog.created_at|date:'M d, Y' }}</span>
                            <h4><a href="{% url 'blogs:detail' pk=p_blog.id %}">{{ p_blog.title }}</a></h4>
                        </div>
                    </li>
                {% endfor %}
            </ul><!-- End .posts-list -->
        </div><!-- End .widget -->

        <div class="widget widget-banner-sidebar">
            <div class="banner-sidebar-title">ad box 280 x 280</div><!-- End .ad-title -->

            <div class="banner-sidebar banner-overlay">
                <a href="#">
                    <img src="{% static 'assets/images/blog/sidebar/banner.jpg' %}" alt="banner">
                </a>
            </div><!-- End .banner-ad -->
        </div><!-- End .widget -->

        <div class="widget">
            <h3 class="widget-title">Browse Tags</h3><!-- End .widget-title -->

            <div class="tagcloud">
                {% for tag in tags %}
                    <a href="#">{{ tag.title }}</a>
                {% endfor %}
            </div><!-- End .tagcloud -->
        </div><!-- End .widget -->
    </div><!-- End .sidebar -->
</aside><!-- End .col-lg-3 -->

templates/blogs/blog-list.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}Blog list{% endblock %}
{% block content %}
    <main class="main">
        <div class="page-header text-center"
             style="background-image: url('{% static 'assets/images/page-header-bg.jpg' %}')">
            <div class="container">
                <h1 class="page-title">Blogs<span>Blog</span></h1>
            </div><!-- End .container -->
        </div><!-- End .page-header -->
        <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Blog</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Listing</li>
                </ol>
            </div><!-- End .container -->
        </nav><!-- End .breadcrumb-nav -->

        <div class="page-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        {% for blog in blogs %}
                            <article class="entry entry-list">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <figure class="entry-media">
                                            <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                <img src="{{ blog.image.url }}"
                                                     alt="image desc">
                                            </a>
                                        </figure><!-- End .entry-media -->
                                    </div><!-- End .col-md-5 -->

                                    <div class="col-md-7">
                                        <div class="entry-body">
                                            <div class="entry-meta">
                                                <span class="entry-author">
                                                    by <a href="#">{{ blog.author.full_name }}</a>
                                                </span>
                                                <span class="meta-separator">|</span>
                                                <a href="#">{{ blog.created_at|date:"M d, Y" }}</a>
                                                <span class="meta-separator">|</span>
                                                <a href="#">Views: {{ blog.views_count }}</a>
                                            </div><!-- End .entry-meta -->

                                            <h2 class="entry-title">
                                                <a href="{% url 'blogs:detail' pk=blog.id %}">{{ blog.title|slice:":50" }}</a>
                                            </h2><!-- End .entry-title -->

                                            <div class="entry-cats">
                                                in
                                                {% for cat in blog.category.all %}
                                                    {% if forloop.last %}
                                                        <a href="#">{{ cat.title }}</a>
                                                    {% else %}
                                                        <a href="#">{{ cat.title }}</a>,
                                                    {% endif %}
                                                {% endfor %}
                                            </div><!-- End .entry-cats -->

                                            <div class="entry-content">
                                                <p>{{ blog.content|slice:":50"|safe }}</p>
                                                <a href="s" class="read-more">Continue Reading</a>
                                            </div><!-- End .entry-content -->
                                        </div><!-- End .entry-body -->
                                    </div><!-- End .col-md-7 -->
                                </div><!-- End .row -->
                            </article><!-- End .entry -->
                        {% endfor %}


                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                <li class="page-item disabled">
                                    <a class="page-link page-link-prev" href="#" aria-label="Previous" tabindex="-1"
                                       aria-disabled="true">
                                        <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>Prev
                                    </a>
                                </li>
                                <li class="page-item active" aria-current="page"><a class="page-link" href="#">1</a>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item">
                                    <a class="page-link page-link-next" href="#" aria-label="Next">
                                        Next <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div><!-- End .col-lg-9 -->

                    {% include 'blogs/blog-left-side.html' %}
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .page-content -->
    </main>
{% endblock %}