apps/accounts/urls.py
from django.urls import path

from apps.accounts.views import RegisterCreateView, LoginFormView, ConfirmEmailView

app_name = "accounts"

urlpatterns = [
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('confirmation/<int:uid>/<str:token>/', ConfirmEmailView.as_view(), name='confirmation'),
]

apps/basket/urls.py
from django.urls import path

from apps.basket.views import basket_detail, basket_add, basket_remove

app_name = 'basket'

urlpatterns = [
    path('', basket_detail, name='detail'),
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:product_id>/', basket_remove, name='basket_remove'),
]

apps/blogs/urls.py
from django.urls import path

from apps.blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

apps/pages/urls.py
from django.urls import path

from apps.pages.views import home_page_view, ContactPageView, about_page_view

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('about/', about_page_view, name='about'),
    path('', home_page_view, name='home'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<!-- molla/blog-listing.html  22 Nov 2019 10:04:10 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Molla - Bootstrap eCommerce Template">
    <meta name="author" content="p-themes">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/images/icons/site.html' %}">
    <link rel="mask-icon" href="{% static 'assets/images/icons/safari-pinned-tab.svg' %}" color="#666666">
    <link rel="shortcut icon" href="{% static 'assets/images/icons/favicon.ico' %}">
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="{% static 'assets/images/icons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <style>
        a {
            cursor: pointer;
        }
    </style>
    {% block extra_css %}{% endblock %}

</head>

<body>
<div class="page-wrapper">
    {% url 'pages:home' as home_url %}
    {% if request.path == home_url %}
        {% include 'layout/header-home.html' %}
    {% else %}
        {% include 'layout/header-base.html' %}
    {% endif %}

    {% block content %}{% endblock %}

    {% include 'layout/footer.html' %}
</div>
<button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

{% include 'layout/mobile-menu.html' %}

{% include 'layout/sign-in-modal.html' %}

<!-- Plugins JS File -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.hoverIntent.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/superfish.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<!-- Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

{% block extra_js %}{% endblock %}
</body>


<!-- molla/blog-listing.html  22 Nov 2019 10:04:12 GMT -->
</html>

templates/layout/footer.html
{% load static %}
<footer class="footer">
        	<div class="footer-middle">
	            <div class="container">
	            	<div class="row">
	            		<div class="col-sm-6 col-lg-3">
	            			<div class="widget widget-about">
	            				<img src="{% static 'assets/images/logo.png' %}" class="footer-logo" alt="Footer Logo" width="105" height="25">
	            				<p>Praesent dapibus, neque id cursus ucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. </p>

	            				<div class="social-icons">
	            					<a href="#" class="social-icon" target="_blank" title="Facebook"><i class="icon-facebook-f"></i></a>
	            					<a href="#" class="social-icon" target="_blank" title="Twitter"><i class="icon-twitter"></i></a>
	            					<a href="#" class="social-icon" target="_blank" title="Instagram"><i class="icon-instagram"></i></a>
	            					<a href="#" class="social-icon" target="_blank" title="Youtube"><i class="icon-youtube"></i></a>
	            					<a href="#" class="social-icon" target="_blank" title="Pinterest"><i class="icon-pinterest"></i></a>
	            				</div><!-- End .soial-icons -->
	            			</div><!-- End .widget about-widget -->
	            		</div><!-- End .col-sm-6 col-lg-3 -->

	            		<div class="col-sm-6 col-lg-3">
	            			<div class="widget">
	            				<h4 class="widget-title">Useful Links</h4><!-- End .widget-title -->

	            				<ul class="widget-list">
	            					<li><a href="../pages/about.html">About Molla</a></li>
	            					<li><a href="#">How to shop on Molla</a></li>
	            					<li><a href="#">FAQ</a></li>
	            					<li><a href="../pages/contact.html">Contact us</a></li>
	            					<li><a href="../auth/login.html">Log in</a></li>
	            				</ul><!-- End .widget-list -->
	            			</div><!-- End .widget -->
	            		</div><!-- End .col-sm-6 col-lg-3 -->

	            		<div class="col-sm-6 col-lg-3">
	            			<div class="widget">
	            				<h4 class="widget-title">Customer Service</h4><!-- End .widget-title -->

	            				<ul class="widget-list">
	            					<li><a href="#">Payment Methods</a></li>
	            					<li><a href="#">Money-back guarantee!</a></li>
	            					<li><a href="#">Returns</a></li>
	            					<li><a href="#">Shipping</a></li>
	            					<li><a href="#">Terms and conditions</a></li>
	            					<li><a href="#">Privacy Policy</a></li>
	            				</ul><!-- End .widget-list -->
	            			</div><!-- End .widget -->
	            		</div><!-- End .col-sm-6 col-lg-3 -->

	            		<div class="col-sm-6 col-lg-3">
	            			<div class="widget">
	            				<h4 class="widget-title">My Account</h4><!-- End .widget-title -->

	            				<ul class="widget-list">
	            					<li><a href="#">Sign In</a></li>
	            					<li><a href="../products/cart.html">View Cart</a></li>
	            					<li><a href="#">My Wishlist</a></li>
	            					<li><a href="#">Track My Order</a></li>
	            					<li><a href="#">Help</a></li>
	            				</ul><!-- End .widget-list -->
	            			</div><!-- End .widget -->
	            		</div><!-- End .col-sm-6 col-lg-3 -->
	            	</div><!-- End .row -->
	            </div><!-- End .container -->
	        </div><!-- End .footer-middle -->

	        <div class="footer-bottom">
	        	<div class="container">
	        		<p class="footer-copyright">Copyright © 2019 Molla Store. All Rights Reserved.</p><!-- End .footer-copyright -->
	        		<figure class="footer-payments">
	        			<img src="{% static 'assets/images/payments.png' %}" alt="Payment methods" width="272" height="20">
	        		</figure><!-- End .footer-payments -->
	        	</div><!-- End .container -->
	        </div><!-- End .footer-bottom -->
        </footer><!-- End .footer -->

templates/layout/header-base.html
{% load static %}
{% load i18n %}
{% load my_tags %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<header class="header">
    <div class="header-top">
        <div class="container">
            <div class="header-left">
                <div class="header-dropdown">
                    <a href="#">Usd</a>
                    <div class="header-menu">
                        <ul>
                            <li><a href="#">Eur</a></li>
                            <li><a href="#">Usd</a></li>
                        </ul>
                    </div><!-- End .header-menu -->
                </div><!-- End .header-dropdown -->

                <div class="header-dropdown">
                    {% get_current_language as current_lang %}
                    {% get_available_languages as all_langs %}
                    <a href="#">{{ current_lang }}</a>
                    <div class="header-menu">
                        <ul>
                            {% for lang in all_langs %}
                                {% if current_lang != lang.0 %}
                                    <li><a href="{% get_full_url request lang.0 %}">{{ lang.0|upper }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div><!-- End .header-menu -->
                </div><!-- End .header-dropdown -->
            </div><!-- End .header-left -->

            <div class="header-right">
                <ul class="top-menu">
                    <li>
                        <a href="#">Links</a>
                        <ul>
                            <li><a href="tel:#"><i class="icon-phone"></i>Call: +0123 456 789</a></li>
                            <li><a href="../products/wishlist.html"><i class="icon-heart-o"></i>Wishlist
                                <span>(3)</span></a></li>
                            <li><a href="../pages/about.html">About Us</a></li>
                            <li><a href="../pages/contact.html">Contact Us</a></li>
                            <li><a href="#signin-modal" data-toggle="modal"><i class="icon-user"></i>Login</a></li>
                        </ul>
                    </li>
                </ul><!-- End .top-menu -->
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-top -->

    <div class="header-middle sticky-header">
        <div class="container">
            <div class="header-left">
                <button class="mobile-menu-toggler">
                    <span class="sr-only">Toggle mobile menu</span>
                    <i class="icon-bars"></i>
                </button>

                <a href="index.html" class="logo">
                    <img src="{% static 'assets/images/logo.png' %}" alt="Molla Logo" width="105" height="25">
                </a>

                <nav class="main-nav">
                    <ul class="menu sf-arrows">
                        {% url 'pages:home' as home_url %}
                        {% url 'pages:contact' as contact_url %}
                        {% url 'blogs:list' as blogs_url %}
                        {% url 'pages:about' as about_url %}
                        {% url 'products:list' as products_url %}
                        <li class="{% if request.path == home_url %}megamenu-container active{% endif %}">
                            <a href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                        </li>
                        <li class="{% if request.path == products_url %}megamenu-container active{% endif %}">
                            <a href="{% url 'products:list' %}">{% trans 'Products' %}</a>
                        </li>
                        <li class="{% if request.path == blogs_url %}megamenu-container active{% endif %}">
                            <a href="{% url 'blogs:list' %}">{% trans 'Blogs' %}</a>
                        </li>
                        <li class="{% if request.path == about_url %}megamenu-container active{% endif %}">
                            <a href="{% url 'pages:about' %}">{% trans 'About' %}</a>
                        </li>
                        <li class="{% if request.path == contact_url %}megamenu-container active{% endif %}">
                            <a href="{% url 'pages:contact' %}">{% trans 'Contact' %}</a>
                        </li>
                    </ul><!-- End .menu -->
                </nav><!-- End .main-nav -->
            </div><!-- End .header-left -->

            <div class="header-right">
                <div class="header-search">
                    <a href="#" class="search-toggle" role="button" title="Search"><i class="icon-search"></i></a>
                    <form action="{% url 'products:list' %}" method="get">
                        <div class="header-search-wrapper">
                            <label for="q" class="sr-only">Search</label>
                            <input value="{{ request.GET.q }}"
                                   type="search" class="form-control" name="q" id="q" placeholder="Search in..."
                                   required>
                        </div><!-- End .header-search-wrapper -->
                    </form>
                </div><!-- End .header-search -->
                <div class="dropdown compare-dropdown">
                    <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false" data-display="static" title="Compare Products"
                       aria-label="Compare Products">
                        <i class="icon-random"></i>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <ul class="compare-products">
                            <li class="compare-product">
                                <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                <h4 class="compare-product-title"><a href="product.html">Blue Night Dress</a></h4>
                            </li>
                            <li class="compare-product">
                                <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                <h4 class="compare-product-title"><a href="product.html">White Long Skirt</a></h4>
                            </li>
                        </ul>

                        <div class="compare-actions">
                            <a href="#" class="action-link">Clear All</a>
                            <a href="#" class="btn btn-outline-primary-2"><span>Compare</span><i
                                    class="icon-long-arrow-right"></i></a>
                        </div>
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .compare-dropdown -->

                <div class="dropdown cart-dropdown">
                    <a href="{% url 'basket:detail' %}" class="dropdown-toggle" role="button" data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false" data-display="static">
                        <i class="icon-shopping-cart"></i>
                        <span class="cart-count">{{ basket|length }}</span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-cart-products">
                            {% for item in basket %}
                                <div class="product">
                                    <div class="product-cart-details">
                                        <h4 class="product-title">
                                            <a href="{% url 'products:detail' pk=item.product.id %}">{{ item.product.title }}</a>
                                        </h4>

                                        <span class="cart-product-info">
                                                <span class="cart-product-qty">{{ item.quantity }}</span>
                                                x ${{ item.product.price }}
                                            </span>
                                    </div><!-- End .product-cart-details -->

                                    <figure class="product-image-container">
                                        <a href="{% url 'products:detail' pk=item.product.id %}" class="product-image">
                                            <img src="{{ item.product.image.url }}"
                                                 alt="product">
                                        </a>
                                    </figure>
                                    <a href="{% url 'basket:basket_remove' product_id=item.product.id %}" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                </div><!-- End .product -->
                            {% endfor %}
                        </div><!-- End .cart-product -->

                        <div class="dropdown-cart-total">
                            <span>Total</span>

                            <span class="cart-total-price">${{ basket.get_total_price }}</span>
                        </div><!-- End .dropdown-cart-total -->

                        <div class="dropdown-cart-action">
                            <a href="{% url 'basket:detail' %}" class="btn btn-primary">View Cart</a>
                            <a href="../products/checkout.html"
                               class="btn btn-outline-primary-2"><span>Checkout</span><i
                                    class="icon-long-arrow-right"></i></a>
                        </div><!-- End .dropdown-cart-total -->
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .cart-dropdown -->
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-middle -->
</header><!-- End .header -->

templates/layout/header-home.html
{% load static %}
{% load i18n %}
{% load my_tags %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<header class="header header-2 header-intro-clearance">
    <div class="header-top">
        <div class="container">
            <div class="header-left">
                <p>Special collection already available.</p><a href="#">&nbsp;Read more ...</a>
            </div><!-- End .header-left -->

            <div class="header-right">

                <ul class="top-menu">
                    <li>
                        <a href="#">Links</a>
                        <ul>
                            <li>
                                <div class="header-dropdown">
                                    <a href="#">USD</a>
                                    <div class="header-menu">
                                        <ul>
                                            <li><a href="#">Eur</a></li>
                                            <li><a href="#">Usd</a></li>
                                        </ul>
                                    </div><!-- End .header-menu -->
                                </div>
                            </li>
                            <li>
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                <div class="header-dropdown">
                                    <a href="#">{{ LANGUAGE_CODE|upper }}</a>
                                    <div class="header-menu">
                                        <ul>
                                            {% for language in languages %}
                                                <li><a href="{% get_full_url request language.code%}">{{ language.code }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div><!-- End .header-menu -->
                                </div>
                            </li>
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:register' %}">Sign in / Sign up</a></li>
                        {% endif %}
                        </ul>
                    </li>
                </ul><!-- End .top-menu -->
            </div><!-- End .header-right -->

        </div><!-- End .container -->
    </div><!-- End .header-top -->

    <div class="header-middle">
        <div class="container">
            <div class="header-left">
                <button class="mobile-menu-toggler">
                    <span class="sr-only">Toggle mobile menu</span>
                    <i class="icon-bars"></i>
                </button>

                <a href="{% url 'pages:home' %}" class="logo">
                    <img src="{% static 'assets/images/demos/demo-2/logo.png' %}" alt="Molla Logo" width="105"
                         height="25">
                </a>
            </div><!-- End .header-left -->

            <div class="header-center">
                <div class="header-search header-search-extended header-search-visible header-search-no-radius d-none d-lg-block">
                    <a href="#" class="search-toggle" role="button"><i class="icon-search"></i></a>
                    <form action="#" method="get">
                        <div class="header-search-wrapper search-wrapper-wide">
                            <label for="q" class="sr-only">Search</label>
                            <input type="search" class="form-control" name="q" id="q" placeholder="Search product ..."
                                   required>
                            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
                        </div><!-- End .header-search-wrapper -->
                    </form>
                </div><!-- End .header-search -->
            </div>

            <div class="header-right">
                <div class="account">
                    <a href="auth/dashboard.html" title="My account">
                        <div class="icon">
                            <i class="icon-user"></i>
                        </div>
                        <p>Account</p>
                    </a>
                </div><!-- End .compare-dropdown -->

                <div class="wishlist">
                    <a href="products/wishlist.html" title="Wishlist">
                        <div class="icon">
                            <i class="icon-heart-o"></i>
                            <span class="wishlist-count badge">3</span>
                        </div>
                        <p>Wishlist</p>
                    </a>
                </div><!-- End .compare-dropdown -->

                <div class="dropdown cart-dropdown">
                    <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false" data-display="static">
                        <div class="icon">
                            <i class="icon-shopping-cart"></i>
                            <span class="cart-count">{{ basket|length }}</span>
                        </div>
                        <p>Cart</p>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-cart-products">
                            {% for item in basket %}
                            <div class="product">
                                <div class="product-cart-details">
                                    <h4 class="product-title">
                                        <a href="{% url 'products:detail' pk=item.product.id %}">Beige knitted elastic runner shoes</a>
                                    </h4>

                                    <span class="cart-product-info">
                                                <span class="cart-product-qty">{{ item.quantity }}</span>
                                                x ${{ item.total_price }}
                                            </span>
                                </div><!-- End .product-cart-details -->

                                <figure class="product-image-container">
                                    <a href="{% url 'products:detail' pk=item.product.id %}" class="product-image">
                                        <img src="{% static 'assets/images/products/cart/product-1.jpg' %}"
                                             alt="product">
                                    </a>
                                </figure>
                                <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                            </div><!-- End .product -->

                            {% endfor %}
                        </div><!-- End .cart-product -->

                        <div class="dropdown-cart-total">
                            <span>Total</span>

                            <span class="cart-total-price">${{ basket.get_total_price }}</span>
                        </div><!-- End .dropdown-cart-total -->

                        <div class="dropdown-cart-action">
                            <a href="products/cart.html" class="btn btn-primary">View Cart</a>
                            <a href="products/checkout.html" class="btn btn-outline-primary-2"><span>Checkout</span><i
                                    class="icon-long-arrow-right"></i></a>
                        </div><!-- End .dropdown-cart-total -->
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .cart-dropdown -->
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-middle -->

    <div class="header-bottom sticky-header">
        <div class="container">
            <div class="header-left">
                <div class="dropdown category-dropdown">
                    <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false" data-display="static" title="Browse Categories">
                        Browse Categories
                    </a>

                    <div class="dropdown-menu">
                        <nav class="side-nav">
                            <ul class="menu-vertical sf-arrows">
                                <li class="item-lead"><a href="#">Daily offers</a></li>
                                <li class="item-lead"><a href="#">Gift Ideas</a></li>
                                <li><a href="#">Beds</a></li>
                                <li><a href="#">Lighting</a></li>
                                <li><a href="#">Sofas & Sleeper sofas</a></li>
                                <li><a href="#">Storage</a></li>
                                <li><a href="#">Armchairs & Chaises</a></li>
                                <li><a href="#">Decoration </a></li>
                                <li><a href="#">Kitchen Cabinets</a></li>
                                <li><a href="#">Coffee & Tables</a></li>
                                <li><a href="#">Outdoor Furniture </a></li>
                            </ul><!-- End .menu-vertical -->
                        </nav><!-- End .side-nav -->
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .category-dropdown -->
            </div><!-- End .header-left -->

            <div class="header-center">
                <nav class="main-nav">
                    <ul class="menu sf-arrows">
                        <li class="megamenu-container active">
                            <a href="{% url 'pages:home' %}" class="sf">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'blogs:list' %}" class="sf">Blogs</a>
                        </li>
                        <li>
                            <a href="{% url 'products:list' %}" class="sf">Products</a>
                        </li>
                        <li>
                            <a href="{% url 'pages:about' %}" class="sf">About</a>
                        </li>
                        <li>
                            <a href="{% url 'pages:contact' %}" class="sf">Contact</a>
                        </li>
                    </ul><!-- End .menu -->
                </nav><!-- End .main-nav -->
            </div><!-- End .header-center -->
        </div><!-- End .container -->
    </div><!-- End .header-bottom -->
</header>